### ISSUE TITLE
Custom validator overwrites other custom validators

### ISSUE THREAD

**Issue by nWidart** [felixkiss/uniquewith-validator#48]
Hello,

I have custom validators set on my project. When required your package, this custom validator overwrites all mine.

Any idea why this is the case ?

Thanks

**Comment by ruscon** [comment]
+1

**Comment by felixkiss** [comment]
What other custom validators do you use?

**Comment by nWidart** [comment]
I have one to validate a folder size, https://github.com/AsgardCms/Media/blob/master/Providers/MediaServiceProvider.php#L78 for example.

**Comment by felixkiss** [comment]
You don't have to use `Validator::resolve()` for this. Replace [this](https://github.com/AsgardCms/Media/blob/master/Providers/MediaServiceProvider.php#L80-L82) with the following and it should work:

```php
Validator::extend('max_size', 'Modules\Media\Validators\MaxFolderSizeValidator@validateMaxSize');
```

And the `MaxFolderSizeValidator` class doesn't have to extend `Validator` anymore.

**Comment by belohlavek** [comment]
I had a similar problem when creating my own validation class (based on the way it' done in this package). It is a completely unrelated validation, but it was being overwritten!

Possible solution, create the instance inside of the `boot()` method instead of the `register()` method in the ServiceProvider:
```
public function boot()
{
    $this->app->validator->resolver(function ($translator, $data, $rules, $messages, $customAttributes = []) {
        return new CustomValidator($translator, $data, $rules, $messages, $customAttributes);
    });
}
```

Not sure if this will introduce undesired situations in the future though, maybe it's a good idea to implement the same technique in this package to avoid conflicts with other people's code. Care to comment on this @felixkiss?

Note: I'm using Lumen without facades
